# Generated by Django 3.2.7 on 2021-10-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/media/photos/thumbnail/empty.png', upload_to='user_profile/'),
        ),
    ]
